### ISSUE TITLE
Crash when starting the server

### ISSUE THREAD

**Issue by CalibanAngel** [LunaPixelStudios/Better-MC#1434]
### Describe the Bug

I'm launching BMC4 in a Docker on a dedicated server but it crash because it failed to load 2 mods, MidnightLib and RyoamicLights

### Reproduction Steps

1. Start a Docker with the following docker-compose
``` yaml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      INIT_MEMORY: '8G'
      MAX_MEMORY: '11G'
      TYPE: "AUTO_CURSEFORGE"
      CF_SLUG: "better-mc-forge-bmc4"
      CF_API_KEY: '...'
    volumes:
      - ./data:/data
```
2. Wait for logs
3. Crash happen

EDIT: if the 2 mods are disabled, the server start well and I can connect to it and play normaly.  

### Crash Report or Log

https://gist.github.com/CalibanAngel/958b2af0dc3bd98cb448e6c5b1e798d1

### Operating System

VM Fedora 36 server edition (Docker)

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v16
