### ISSUE TITLE
Jellyfish falling from the sky and in caves

### ISSUE THREAD

**Issue by deftesthawk** [LunaPixelStudios/Better-MC#1608]
### Describe the Bug

There is a bug with the Hybrid Aquatic mod that causes jellyfish to spawn in the sky when building stuff high up and also spawn in some large caves. I found a work around for this bug using the "Mob Filter" mod if anyone is interested just put this in the config :)
```
rules:

 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:atolla_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:barrel_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:blue_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:cauliflower_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:compass_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:fried_egg_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:lions_mane_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:moon_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
 - name: Disable jellyfish spawning out of water
   what: DISALLOW_SPAWN
   when:
     entityId: ['hybrid-aquatic:nomura_jellyfish']
     blockId: ['minecraft:air', 'minecraft:cave_air']
```

### Reproduction Steps

1. Look around large caves some times they fall from the roofs and leave slime balls 
2. Build cobblestone up to y200 while climbing a ladder to go up it you'll see them spawning

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc2 v24
