### ISSUE TITLE
Crash on Docker Server Startup

### ISSUE THREAD

**Issue by lindi200000** [LunaPixelStudios/Better-MC#1740]
### Describe the Bug

```
[14:18:10] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
   - Install §6necronomicon§r, version 1.3.0 or later.
More details:
   - §Emod Eldritch End (eldritch_end)§r 0.2.31 requires version 1.3.0 or later of §6necronomicon§r, which is missing!
```

### Reproduction Steps

1. Set up Docker with the following docker-compose.yml configuration:
```
mc-better:
    container_name: mc-better
    image: itzg/minecraft-server:java17
    volumes:
    - mc-better-mods:/modpacks:ro
    - mc-better-data:/data
    - /etc/localtime:/etc/localtime:ro 
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      EULA: 'true'
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: '$$2a$$10$$DiHxxxxxKt1dq2Nci9s6xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxx/xxxx'
      CF_SLUG: better-mc-forge-bmc4
      MEMORY: 10G
      DIFFICULTY: normal
      SERVER_NAME: 'Kids World'
    ports:
      - "25565:25565"
```
2. Start the server using Docker: docker-compose up.
3. Observe the server start-up process and the resulting error message indicating the mod incompatibility.

### Operating System

PhotonOS / Docker version 24.0.5

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

better-mc-forge-bmc4 v28
