### ISSUE TITLE
Cannot create Server using docker-compose setup

### ISSUE THREAD

**Issue by da-stoaz** [LunaPixelStudios/Better-MC#1758]
### Describe the Bug
I wanted to set up a Minecraft Server in Docker, but Errors occur in the creation of the container (first start). As a result, the container does not start at all.

### Reproduction Steps

1. I created a docker-compose file which looks like this:
`services:
  minecraft:
    image: itzg/minecraft-server
    container_name: MC-BMC    # Give the container a name
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      INIT_MEMORY: '6G'
      MEMORY: '10G'
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: <Key>
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4/files/5418297"
      FORGEVERSION: "latest"        # Specify the Forge version compatible with your Minecraft version
    volumes:
      - ~/MC-BMC/data:/data                # Persist Minecraft data
      - ~/MC-BMC/mods:/data/mods           # Mount mods directory`
2. I started it using "docker-compose up -d"
3.
...

### Screenshots and Videos

[logs.txt](https://github.com/user-attachments/files/16365358/logs.txt)

### Operating System

Linux Ubuntu

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

No additional mods

**Comment by mjftw** [comment]
I also have this problem. My Minecraft server uses the docker image and this bug means I can't use Better-MC :(

**Comment by kStor2poche** [comment]
You can adapt it by using the example provided by the [https://github.com/itzg/docker-minecraft-server/blob/master/examples/bmc4/docker-compose.yml](itzg github) : 
```yaml
services:
  mc:
    image: itzg/minecraft-server:java17
    environment:
      EULA: true
      TYPE: MODRINTH
      VERSION: 1.20.1
      MEMORY: 10G
      MODRINTH_MODPACK: better-mc-forge-bmc4
      MODRINTH_VERSION: v28
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        mods/NekosEnchantedBooks-*.jar
        mods/citresewn-*.jar
      MODS_FILE: /extras/mods.txt
      ENABLE_WHITELIST: false
      MAX_PLAYERS: 5
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      PVP: "true"
      TZ: "Europa/Paris"
    volumes:
      - data:/data
      - ./mods.txt:/extras/mods.txt:ro
    ports:
      - "25565:25565"

volumes:
  data: {}
```
